import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/NavbarDashboard";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${inter.className}`}
            >
                <div className="relative h-screen flex flex-col">
                    <Navbar />
                    <div className="flex-1 overflow-y-auto">
                        <div className="bg-gray-200 h-screen flex flex-col">
                            <div className="flex flex-1 h-4/5">
                                <main className="flex-1 overflow-auto">{children}</main>
                            </div>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
